### ISSUE TITLE
Pull information from the GUI/app.

### ISSUE THREAD

**Issue by alexgphan** [xubosen/CSC207-Project-Group-262#59]
How would we pull information on who is currently logged in.

While I was working on create course we would need to check whether the user logged in is a Instructor to give them the option of creating a course. Same for creating a Event and Session. Depending on the users role the myCourse, myEvents and mySessions view would differ.

I was also thinking about the layout that Simon mentioned where we would click on courses to then access events which would allow you to access sessions and was wondering how we would pull the information of the previous page pulled up. From the layout above the create event button would automatically be creating an event from the previously clicked course. How would we get the previously clicked course as inputdata?

**Comment by Fourstarfish** [comment]
One of the solutions I came up with was using the Button's label as a clue for what course we are gonna want to create an event for. The button's label is always going to be the course code ("CSC207") for example. We could use that string, and then search the InMemoryCourseDataAccessObject for the course using that String. That should let us get the course we need for which we want to create an event for.

**Comment by xubosen** [comment]
Current implementation is using a UserState object that stores the id and "type" of the user that is logged in. This is then passed around until the user logs out, at which point it would be cleared.
