### ISSUE TITLE
Enroll Use Case TODO

### ISSUE THREAD

**Issue by Fourstarfish** [xubosen/CSC207-Project-Group-262#63]
There seems to be a TODO in the EnrollController which pertains to enrolling using email instead of userID. I personally think that userID works fine, but what do you guys think?

If userID is okay, the TODO should be deleted.

**Comment by alexgphan** [comment]
I think Simon was originally going to bring this up during a meeting so we would need to wait for his input.
Since it's already completed using userID we can probably delete the todo and just put it inside the google doc as a future option.
